services:
  dev:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
      - '5173:5173'
    volumes:
      - ./src:/app/src
      - ./server.js:/app/server.js
      - ./.env:/app/.env
      - ./vite.config.js:/app/vite.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./index.html:/app/index.html
    environment:
      - AZURE_OPENAI_ACCOUNT_NAME=${AZURE_OPENAI_ACCOUNT_NAME}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_CHAT_DEPLOYMENT=${AZURE_OPENAI_CHAT_DEPLOYMENT}
      - VITE_AUDIOS_CONTAINER_NAME=${VITE_AUDIOS_CONTAINER_NAME}
      - VITE_SERVICE_REGION=${VITE_SERVICE_REGION}
      - VITE_SPEECH_ENDPOINT=${VITE_SPEECH_ENDPOINT}
      - VITE_SPEECH_KEY=${VITE_SPEECH_KEY}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - COSMOSDB_CONNECTION_STRING=${COSMOSDB_CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}
      - VITE_PAYFAST_MERCHANT_ID=${VITE_PAYFAST_MERCHANT_ID}
      - VITE_PAYFAST_MERCHANT_KEY=${VITE_PAYFAST_MERCHANT_KEY}
      - VITE_PAYFAST_PASSPHRASE=${VITE_PAYFAST_PASSPHRASE}
      - VITE_PAYFAST_SANDBOX=${VITE_PAYFAST_SANDBOX}
      - VITE_API_URL=${VITE_API_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - AZURE_COMMUNICATION_CONNECTION_STRING=${AZURE_COMMUNICATION_CONNECTION_STRING}
      - AZURE_SENDER_EMAIL=${AZURE_SENDER_EMAIL}
      - NODE_ENV=${NODE_ENV}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

networks:
  default:
    name: legal-scriber-network
