services:
  dev:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
      - '5173:5173'
    volumes:
      - ./src:/app/src
      - ./server.js:/app/server.js
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - VITE_SERVICE_REGION=${VITE_SERVICE_REGION}
      - VITE_SPEECH_KEY=${VITE_SPEECH_KEY}
      - VITE_SPEECH_ENDPOINT=${VITE_SPEECH_ENDPOINT}
      - VITE_AUDIOS_CONTAINER_NAME=${VITE_AUDIOS_CONTAINER_NAME}
      - AZURE_OPENAI_ACCOUNT_NAME=${AZURE_OPENAI_ACCOUNT_NAME}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - COSMOSDB_CONNECTION_STRING=${COSMOSDB_CONNECTION_STRING}
      - NODE_ENV=development
    command: npm run dev

networks:
  default:
    name: legal-scriber-network
