services:
  prod:
    # image: thandosomacele/legalscriber:latest
    build:
      context: .
      target: production
    ports:
      - '3001:3001'
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - VITE_SERVICE_REGION=${VITE_SERVICE_REGION}
      - VITE_SPEECH_KEY=${VITE_SPEECH_KEY}
      - VITE_SPEECH_ENDPOINT=${VITE_SPEECH_ENDPOINT}
      - VITE_AUDIOS_CONTAINER_NAME=${VITE_AUDIOS_CONTAINER_NAME}
      - AZURE_OPENAI_ACCOUNT_NAME=${AZURE_OPENAI_ACCOUNT_NAME}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - NODE_ENV=production
      - DOCKER_BUILDKIT=1
    command: npm start
