services:
  prod:
    # image: thandosomacele/legalscriber:latest
    build:
      context: .
      target: production
    ports:
      - '8000:8000'
    environment:
      - AZURE_OPENAI_ACCOUNT_NAME=${AZURE_OPENAI_ACCOUNT_NAME}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_CHAT_DEPLOYMENT=${AZURE_OPENAI_CHAT_DEPLOYMENT}
      - VITE_AUDIOS_CONTAINER_NAME=${VITE_AUDIOS_CONTAINER_NAME}
      - VITE_SERVICE_REGION=${VITE_SERVICE_REGION}
      - VITE_SPEECH_ENDPOINT=${VITE_SPEECH_ENDPOINT}
      - VITE_SPEECH_KEY=${VITE_SPEECH_KEY}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - COSMOSDB_CONNECTION_STRING=${COSMOSDB_CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}
      - VITE_PAYFAST_MERCHANT_ID=${VITE_PAYFAST_MERCHANT_ID}
      - VITE_PAYFAST_MERCHANT_KEY=${VITE_PAYFAST_MERCHANT_KEY}
      - VITE_PAYFAST_PASSPHRASE=${VITE_PAYFAST_PASSPHRASE}
      - VITE_PAYFAST_SANDBOX=${VITE_PAYFAST_SANDBOX}
      - VITE_API_URL=${VITE_API_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - AZURE_COMMUNICATION_CONNECTION_STRING=${AZURE_COMMUNICATION_CONNECTION_STRING}
      - AZURE_SENDER_EMAIL=${AZURE_SENDER_EMAIL}
      - NODE_ENV=production
    command: npm start
