services:
  app:
    build:
      context: .
      target: build
    ports:
      - '3000:3000'
      - '5173:5173'
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev
